name: CI
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Godot Export
        uses: firebelley/godot-export@v5.2.1
        with:
          # The download url of the Linux Headless Godot executable.
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_linux.x86_64.zip
          # The url of the export templates corresponding to the Godot executable version
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.2/Godot_v4.2.2-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          cache: true
      # https://github.com/ncipollo/release-action
      - name: Delete Release
        uses: larryjoelane/delete-release-action@v1.0.24
        with:
            release-name: pre-release-${{github.ref_name}}
            token: ${{ secrets.GITHUB_TOKEN }}
          
      
      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            generateReleaseNotes: true
            tag: pre-release-${{github.ref_name}}
            artifacts: /home/runner/.local/share/godot/archives/Windows\ Desktop.zip
            allowUpdates: true  # Allow updates to existing releases
